'use client';

import React, { useState, useEffect } from 'react';
import { AgentDecision } from '@/lib/types';

interface WhyThisModalProps {
  isOpen: boolean;
  onClose: () => void;
  decisionId?: string;
  directDecision?: {
    reason_code?: string;
    reason_text?: string;
    evidence?: Record<string, any>;
    action?: string;
    kind?: string;
  };
}

export default function WhyThisModal({
  isOpen,
  onClose,
  decisionId,
  directDecision,
}: WhyThisModalProps) {
  const [decision, setDecision] = useState<AgentDecision | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isOpen) return;

    if (directDecision) {
      setDecision({
        id: 'direct',
        user_id: '',
        kind: directDecision.kind as any || 'practice',
        action: directDecision.action || 'intervention',
        reason_code: directDecision.reason_code || 'adaptive_engine',
        reason_text: directDecision.reason_text || 'Recommended by the Autonomous Adaptive Engine based on your learning history.',
        evidence: directDecision.evidence || {},
        created_at: new Date().toISOString(),
      });
      return;
    }

    if (decisionId) {
      setLoading(true);
      fetch(`/api/adaptive-engine?decisionId=${encodeURIComponent(decisionId)}`)
        .then((res) => res.json())
        .then((data) => {
          if (data.decision) {
            setDecision(data.decision);
          }
        })
        .catch(() => {})
        .finally(() => setLoading(false));
    }
  }, [isOpen, decisionId, directDecision]);

  if (!isOpen) return null;

  const evidence = decision?.evidence || {};
  const hasEvidence = Object.keys(evidence).length > 0;

  return (
    <div className="fixed inset-0 z-[200] bg-ink/70 backdrop-blur-xs flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-card border border-border rounded-[22px] max-w-md w-full p-6 shadow-2xl space-y-4 animate-scale-in">
        <div className="flex items-center justify-between pb-3 border-b border-border">
          <div className="flex items-center gap-2">
            <span className="text-xl">💡</span>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-amber block">
                Autonomous Decision Logic
              </span>
              <h3 className="font-serif font-bold text-base text-ink">Why am I being recommended this?</h3>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 rounded-full bg-card-alt border border-border flex items-center justify-center text-xs text-muted hover:text-ink cursor-pointer transition-colors"
          >
            ✕
          </button>
        </div>

        {loading ? (
          <div className="py-8 text-center text-xs text-muted">
            <div className="w-5 h-5 border-2 border-amber border-t-transparent rounded-full animate-spin mx-auto mb-2" />
            Loading decision audit trail...
          </div>
        ) : (
          <div className="space-y-3.5 text-xs">
            {/* Primary Reason Text */}
            <div className="p-3.5 bg-amber/10 border border-amber/25 rounded-xl">
              <p className="font-medium text-ink leading-relaxed">
                {decision?.reason_text || 'This recommendation was generated by the adaptive engine based on your topic mastery records.'}
              </p>
            </div>

            {/* Evidence Breakdown (Hard Rule: numbers from database, never made up) */}
            {hasEvidence && (
              <div className="bg-card-alt border border-border rounded-xl p-3.5 space-y-2">
                <span className="text-[10px] font-bold uppercase tracking-wider text-muted block">
                  Observed Signals &amp; Evidence
                </span>
                <div className="space-y-1.5 text-[11px]">
                  {evidence.score !== undefined && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Assessment Score</span>
                      <span className="font-bold text-ink">{evidence.score}% (Threshold: {evidence.threshold ?? 70}%)</span>
                    </div>
                  )}

                  {evidence.prerequisiteTopic && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Prerequisite Topic</span>
                      <span className="font-bold text-ink">
                        {evidence.prerequisiteTopic} ({evidence.prerequisiteMastery ?? 0}%)
                      </span>
                    </div>
                  )}

                  {Array.isArray(evidence.weakSubtopics) && evidence.weakSubtopics.length > 0 && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Weak Subtopics</span>
                      <span className="font-bold text-ink">{evidence.weakSubtopics.join(', ')}</span>
                    </div>
                  )}

                  {evidence.skippedSessions !== undefined && evidence.skippedSessions > 0 && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Skipped Sessions</span>
                      <span className="font-bold text-bad">{evidence.skippedSessions}</span>
                    </div>
                  )}

                  {evidence.abandonedAssessments !== undefined && evidence.abandonedAssessments > 0 && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Abandoned Assessments</span>
                      <span className="font-bold text-bad">{evidence.abandonedAssessments}</span>
                    </div>
                  )}

                  {evidence.practiceCompletionPct !== undefined && (
                    <div className="flex justify-between items-center py-0.5 border-b border-border/50">
                      <span className="text-muted">Practice Completion</span>
                      <span className="font-bold text-ink">{evidence.practiceCompletionPct}%</span>
                    </div>
                  )}

                  {evidence.date && (
                    <div className="flex justify-between items-center py-0.5">
                      <span className="text-muted">Logged Date</span>
                      <span className="font-mono text-muted">{evidence.date}</span>
                    </div>
                  )}
                </div>
              </div>
            )}

            <div className="pt-2 flex justify-end">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 bg-amber hover:bg-terracotta text-white font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
              >
                Got it
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
